# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20180706_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
