# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='Images',
        ),
    ]
